refetch:
  rm -r vendor/
  mkdir vendor/
  curl -L https://github.com/wiredtiger/wiredtiger/archive/refs/tags/3.1.0.tar.gz | tar --extract --directory vendor/
  cd vendor/wiredtiger-3.1.0 && ./autogen.sh
  rm vendor/wiredtiger-3.1.0/.gitignore
