refetch:
  rm -r vendor/
  mkdir vendor/
  curl -L https://github.com/wiredtiger/wiredtiger/archive/refs/tags/10.0.0.tar.gz | tar --extract --directory vendor/
  cd vendor/wiredtiger-10.0.0 && ./autogen.sh
  rm vendor/wiredtiger-10.0.0/.gitignore
